# Generated by Django 2.2.1 on 2019-05-12 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataAsli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penyakit', models.TextField()),
                ('gejala', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NamaGejala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gejala', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NamaPenyakit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penyakit', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PenyakitGejala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gejala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='daftarPenyakit.NamaGejala')),
                ('penyakit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='daftarPenyakit.NamaPenyakit')),
            ],
        ),
    ]
